// Generated by GitHub Copilot
import React, { useState, useEffect } from 'react';
import { Game } from '@/core/Game';
import { Position, GamePhase, PieceType, GameStatus, PlayerType, Move } from '@/core/types';
import { AIEngine } from '@/ai/AIEngine';
import { AIFactory } from '@/ai/AIFactory';
import BoardCanvas from '../Board/BoardCanvas';
import FullscreenBoard from '../Board/FullscreenBoard';
import GameInfo from './GameInfo';
import GameToolbar from './GameToolbar';
import MoveHistory from './MoveHistory';
import MoveAnalysis from '../AI/MoveAnalysis';
import GameStatistics from './GameStatistics';
import RulesModal from '../Tutorial/RulesModal';
import WelcomeModal from '../Tutorial/WelcomeModal';
import DrawOfferModal from './DrawOfferModal';
import { GameStatisticsTracker, GameRecord, MoveRecord } from '@/utils/gameStatistics';
import { useKeyboardShortcuts } from '@/hooks/useKeyboardShortcuts';
import { useAIWorker } from '@/hooks/useAIWorker';
import { playMoveSound, playCaptureSound, playWinSound } from '@/utils/sounds';

type GameMode = 'human-vs-human' | 'human-vs-ai' | 'ai-vs-human';

const GameContainer: React.FC = () => {
  const [game] = useState(() => new Game());
  const [gameState, setGameState] = useState(game.getState());
  const [selectedPosition, setSelectedPosition] = useState<Position | null>(null);
  const [highlightedPositions, setHighlightedPositions] = useState<Position[]>([]);
  const [lastMove, setLastMove] = useState<Move | null>(null);

  // AI state
  const [gameMode, setGameMode] = useState<GameMode>('human-vs-ai');
  const [aiDifficulty, setAiDifficulty] = useState<number>(2); // Default to Medium
  const [aiEngine, setAiEngine] = useState<AIEngine | null>(null);
  const [isAIThinking, setIsAIThinking] = useState(false);
  const { computeMove } = useAIWorker();

  // Game tracking
  const [gameStartTime, setGameStartTime] = useState<number>(Date.now());
  const [moveRecords, setMoveRecords] = useState<MoveRecord[]>([]);

  // UI state
  const [isRulesModalOpen, setIsRulesModalOpen] = useState(false);
  const [isStatsOpen, setIsStatsOpen] = useState(false);
  const [isModePickerOpen, setIsModePickerOpen] = useState(true);
  const [isWelcomeModalOpen, setIsWelcomeModalOpen] = useState(() => {
    const hasVisited = localStorage.getItem('baghchal_has_visited');
    return !hasVisited;
  });
  const [isFullscreen, setIsFullscreen] = useState(false);
  // Track whether we've already played the win sound for this game
  const [winSoundPlayed, setWinSoundPlayed] = useState(false);

  // Draw offer state
  const [isDrawOfferOpen, setIsDrawOfferOpen] = useState(false);
  const [drawOfferReason, setDrawOfferReason] = useState<'repetition' | 'no-progress'>('repetition');
  // The repetition count at which the user last declined (re-prompt at next multiple of 3)
  const [drawDeclinedAt, setDrawDeclinedAt] = useState(0);
  // Track last goatsCaptured + goatsRemaining to detect progress and reset drawDeclinedAt
  const [lastProgressSnapshot, setLastProgressSnapshot] = useState({ captured: 0, remaining: 20 });

  // Initialize AI engine
  useEffect(() => {
    const engine = AIFactory.createFromLevel(aiDifficulty);
    setAiEngine(engine);
  }, [aiDifficulty]);

  // Mark as visited when welcome modal closes
  const handleWelcomeClose = () => {
    localStorage.setItem('baghchal_has_visited', 'true');
    setIsWelcomeModalOpen(false);
  };

  const handleWelcomeShowRules = () => {
    setIsRulesModalOpen(true);
  };

  // Keyboard shortcuts
  useKeyboardShortcuts({
    onUndo: () => {
      if (gameState.moveHistory.length > 0 && !isAIThinking && !isCurrentPlayerAI()) {
        handleUndo();
      }
    },
    onNewGame: () => {
      if (gameState.status !== GameStatus.IN_PROGRESS) {
        setIsModePickerOpen(true);
      }
    },
    onShowRules: () => {
      setIsRulesModalOpen(true);
    },
    onToggleFullscreen: () => {
      setIsFullscreen(!isFullscreen);
    },
    onEscape: () => {
      if (isFullscreen) {
        setIsFullscreen(false);
      } else if (isRulesModalOpen) {
        setIsRulesModalOpen(false);
      } else if (isWelcomeModalOpen) {
        handleWelcomeClose();
      }
    },
  });

  // Update game state
  const updateGameState = () => {
    setGameState(game.getState());
  };

  // Check if current player is AI
  const isCurrentPlayerAI = (): boolean => {
    if (gameMode === 'human-vs-human') return false;
    if (gameMode === 'human-vs-ai') {
      return gameState.currentPlayer === PlayerType.TIGER;
    }
    if (gameMode === 'ai-vs-human') {
      return gameState.currentPlayer === PlayerType.GOAT;
    }
    return false;
  };

  // Make AI move
  const makeAIMove = async () => {
    if (!aiEngine || isAIThinking || game.isGameOver()) return;

    setIsAIThinking(true);

    const pickFallbackMove = (validMoves: Array<{ move: Move; isCapture: boolean }>): Move | null => {
      if (validMoves.length === 0) return null;

      // Prefer captures when no evaluator is available
      if (!aiEngine.evaluate) {
        const capture = validMoves.find((vm) => vm.isCapture);
        return capture ? capture.move : validMoves[0].move;
      }

      let bestMove = validMoves[0].move;
      let bestEval = -Infinity;

      for (const vm of validMoves) {
        const simGame = game.clone();
        const success = simGame.makeMove(vm.move);
        if (!success) continue;

        const evalScore = aiEngine.evaluate(simGame.getState(), gameState.currentPlayer);
        if (evalScore > bestEval) {
          bestEval = evalScore;
          bestMove = vm.move;
        }
      }

      return bestMove;
    };

    try {
      // Brief delay for UX (let user see the thinking indicator)
      await new Promise((resolve) => setTimeout(resolve, 150));

      const move = await computeMove(gameState, gameState.currentPlayer, aiDifficulty);

      // Make the move
      const success = game.makeMove(move);
      if (success) {
        move.captured ? playCaptureSound() : playMoveSound();
        setLastMove(move);
        setSelectedPosition(null);
        setHighlightedPositions([]);
        updateGameState();
      } else {
        // If AI returned invalid move, use a scored fallback
        console.error('AI returned invalid move, using fallback', move);
        const validMoves = game.getValidMoves();
        const fallbackMove = pickFallbackMove(validMoves);
        if (fallbackMove) {
          const fallbackSuccess = game.makeMove(fallbackMove);
          if (fallbackSuccess) {
            playMoveSound();
            setLastMove(fallbackMove);
            setSelectedPosition(null);
            setHighlightedPositions([]);
            updateGameState();
          }
        } else {
          console.error('No valid moves available - game should be over');
        }
      }
    } catch (error) {
      console.error('AI move error:', error);
      try {
        const validMoves = game.getValidMoves();
        const fallbackMove = pickFallbackMove(validMoves);
        if (fallbackMove) {
          game.makeMove(fallbackMove);
          setLastMove(fallbackMove);
          updateGameState();
        }
      } catch (fallbackError) {
        console.error('Fallback move also failed', fallbackError);
      }
    } finally {
      setIsAIThinking(false);
    }
  };

  // Trigger AI move when it's AI's turn
  useEffect(() => {
    if (isCurrentPlayerAI() && gameState.status === GameStatus.IN_PROGRESS && !isDrawOfferOpen) {
      makeAIMove();
    }
  }, [gameState.currentPlayer, gameState.status, gameMode, isDrawOfferOpen]);

  // Handle point click
  const handlePointClick = (position: Position) => {
    // Ignore clicks when AI is thinking or it's AI's turn
    if (isAIThinking || isCurrentPlayerAI()) return;

    const piece = game.getBoard().getPiece(position);
    const currentPieceType =
      gameState.currentPlayer === PlayerType.TIGER ? PieceType.TIGER : PieceType.GOAT;

    // Special case: Placement phase with goat player clicking empty space
    if (
      gameState.phase === GamePhase.PLACEMENT &&
      gameState.currentPlayer === PlayerType.GOAT &&
      piece === PieceType.EMPTY
    ) {
      const move = { from: null, to: position, captured: null };
      const success = game.makeMove(move);
      if (success) {
        playMoveSound();
        setLastMove(move);
        setSelectedPosition(null);
        setHighlightedPositions([]);
        updateGameState();
      }
      return;
    }

    // For all other cases (tiger in placement phase, or movement phase for both):
    // If no piece is selected
    if (selectedPosition === null) {
      // Check if clicked position has a piece belonging to current player
      if (piece === currentPieceType) {
        // Select this piece
        setSelectedPosition(position);

        // Get valid moves from this position
        const validMoves = game.getValidMovesFrom(position);
        const highlights = validMoves.map((vm) => vm.move.to);
        setHighlightedPositions(highlights);
      }
    } else {
      // A piece is already selected
      // Check if clicked position is a valid move destination
      const validMoves = game.getValidMovesFrom(selectedPosition);
      const validMove = validMoves.find(
        (vm) => vm.move.to.row === position.row && vm.move.to.col === position.col
      );

      if (validMove) {
        const success = game.makeMove(validMove.move);
        if (success) {
          validMove.move.captured ? playCaptureSound() : playMoveSound();
          setLastMove(validMove.move);
          setSelectedPosition(null);
          setHighlightedPositions([]);
          updateGameState();
        }
      } else {
        // Check if clicked on another piece of the same type
        if (piece === currentPieceType) {
          // Select the new piece
          setSelectedPosition(position);
          const validMoves = game.getValidMovesFrom(position);
          const highlights = validMoves.map((vm) => vm.move.to);
          setHighlightedPositions(highlights);
        } else {
          // Deselect
          setSelectedPosition(null);
          setHighlightedPositions([]);
        }
      }
    }
  };

  // Save game statistics when game ends
  const saveGameStatistics = () => {
    if (gameState.status === GameStatus.IN_PROGRESS) return;
    if (gameMode === 'human-vs-human') return; // Only track vs AI games

    const humanSide = gameMode === 'human-vs-ai' ? PlayerType.GOAT : PlayerType.TIGER;
    const winner =
      gameState.status === GameStatus.DRAW
        ? null
        : gameState.status === GameStatus.TIGER_WIN
          ? PlayerType.TIGER
          : PlayerType.GOAT;

    const gameRecord: GameRecord = {
      id: `game_${Date.now()}`,
      timestamp: gameStartTime,
      mode: gameMode,
      aiDifficulty,
      humanSide,
      winner,
      totalMoves: gameState.turnNumber,
      duration: Date.now() - gameStartTime,
      goatsCaptured: gameState.goatsCaptured,
      moves: moveRecords,
      finalState: gameState,
    };

    GameStatisticsTracker.saveGame(gameRecord);
    console.log('Game statistics saved', gameRecord);
  };

  // Detect game end: save statistics and play win sound
  useEffect(() => {
    if (gameState.status !== GameStatus.IN_PROGRESS) {
      setTimeout(() => {
        saveGameStatistics();
      }, 500);
      if (!winSoundPlayed) {
        setWinSoundPlayed(true);
        setTimeout(() => playWinSound(), 200);
      }
    }
  }, [gameState.status]);

  // Detect repetition / stuck game and offer draw
  useEffect(() => {
    if (gameState.status !== GameStatus.IN_PROGRESS) return;
    if (isDrawOfferOpen) return;

    // Reset drawDeclinedAt when progress happens (capture or placement)
    const { captured, remaining } = lastProgressSnapshot;
    if (gameState.goatsCaptured !== captured || gameState.goatsRemaining !== remaining) {
      setLastProgressSnapshot({ captured: gameState.goatsCaptured, remaining: gameState.goatsRemaining });
      setDrawDeclinedAt(0);
    }

    const repCount = game.getRepetitionCount();
    const noProgress = game.getMovesSinceProgress();

    // Threefold repetition: prompt at 3, then at every subsequent multiple of 3 past the declined threshold
    if (repCount >= 3 && repCount > drawDeclinedAt) {
      setDrawOfferReason('repetition');
      setIsDrawOfferOpen(true);
      return;
    }

    // No-progress safety net: 200 consecutive moves without capture/placement (movement phase only)
    if (noProgress >= 200 && noProgress > drawDeclinedAt) {
      setDrawOfferReason('no-progress');
      setIsDrawOfferOpen(true);
    }
  }, [gameState.turnNumber]);

  // Handle new game
  const handleNewGame = () => {
    game.reset();
    setSelectedPosition(null);
    setHighlightedPositions([]);
    setLastMove(null);
    setGameStartTime(Date.now());
    setMoveRecords([]);
    setWinSoundPlayed(false);
    setIsDrawOfferOpen(false);
    setDrawDeclinedAt(0);
    setLastProgressSnapshot({ captured: 0, remaining: 20 });
    updateGameState();
  };

  const startNewGameWithMode = (mode: GameMode) => {
    setGameMode(mode);
    handleNewGame();
    setIsModePickerOpen(false);
  };

  const handleRequestNewGame = () => {
    setIsModePickerOpen(true);
  };

  // Handle undo
  const handleUndo = () => {
    if (isAIThinking || gameState.moveHistory.length === 0) return;

    let undoneCount = 0;

    if (gameMode === 'human-vs-human') {
      if (game.undoMove()) {
        undoneCount = 1;
      }
    } else {
      // In AI modes, undo back to the previous human decision point:
      // usually this means undo AI move + human move.
      const humanPlayer = gameMode === 'human-vs-ai' ? PlayerType.GOAT : PlayerType.TIGER;

      while (game.getState().moveHistory.length > 0) {
        const success = game.undoMove();
        if (!success) break;
        undoneCount++;

        if (game.getCurrentPlayer() === humanPlayer) {
          break;
        }
      }
    }

    if (undoneCount > 0) {
      setMoveRecords((prev) => prev.slice(0, Math.max(0, prev.length - undoneCount)));
      setSelectedPosition(null);
      setHighlightedPositions([]);
      setLastMove(null);
      updateGameState();
    }
  };

  // Show instructions for placement phase
  const getInstructions = () => {
    if (gameState.status !== GameStatus.IN_PROGRESS) {
      return '';
    }

    if (isAIThinking) {
      return 'AI is calculating the best move...';
    }

    if (isCurrentPlayerAI()) {
      return 'AI is playing...';
    }

    if (gameState.phase === GamePhase.PLACEMENT) {
      if (gameState.currentPlayer === PlayerType.GOAT) {
        return 'Click on an empty point to place a goat';
      } else {
        return 'Click on your tiger to select it, then click on a highlighted point to move or capture';
      }
    } else {
      return 'Click on your piece to select it, then click on a highlighted point to move';
    }
  };

  // Handle game mode change
  const handleGameModeChange = (mode: GameMode) => {
    startNewGameWithMode(mode);
  };

  return (
    <div className="w-full max-w-7xl mx-auto">

      {/* ── Compact toolbar: mode + difficulty + actions ── */}
      <GameToolbar
        gameMode={gameMode}
        onGameModeChange={handleGameModeChange}
        aiDifficulty={aiDifficulty}
        onDifficultyChange={setAiDifficulty}
        onNewGame={handleRequestNewGame}
        onUndo={handleUndo}
        onOpenRules={() => setIsRulesModalOpen(true)}
        onOpenStats={() => setIsStatsOpen(true)}
        canUndo={!isAIThinking && gameState.moveHistory.length > 0 && !isCurrentPlayerAI()}
        gameStatus={gameState.status}
        isAIThinking={isAIThinking}
      />

      {/* ── Instructions / AI thinking indicator ── */}
      <div className="mb-3 min-h-[2.5rem] flex items-center justify-center">
        <p className="text-sm md:text-base text-gray-600 font-medium text-center">
          {getInstructions()}
        </p>
      </div>

      {/* ── Main game grid ── */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Board — 2 columns on lg */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-lg shadow-lg p-4 md:p-6 relative">
            {isAIThinking && (
              <div className="absolute top-4 left-4 z-10 pointer-events-none">
                <div
                  className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full border shadow-sm backdrop-blur-sm text-xs font-semibold ${
                    gameState.currentPlayer === PlayerType.TIGER
                      ? 'bg-orange-50/95 border-orange-200 text-orange-700'
                      : 'bg-green-50/95 border-green-200 text-green-700'
                  }`}
                >
                  <span
                    className={`w-2 h-2 rounded-full animate-pulse ${
                      gameState.currentPlayer === PlayerType.TIGER ? 'bg-orange-500' : 'bg-green-500'
                    }`}
                  />
                  <span>AI thinking</span>
                </div>
              </div>
            )}
            <button
              onClick={() => setIsFullscreen(true)}
              className="absolute top-4 right-4 z-10 w-10 h-10 bg-white/80 hover:bg-gradient-to-r hover:from-orange-500 hover:to-amber-500 text-gray-600 hover:text-white rounded-lg shadow-md transition-all duration-200 transform hover:scale-110 flex items-center justify-center"
              aria-label="Expand board to fullscreen (press F)"
              title="Fullscreen (F)"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
              </svg>
            </button>
            <BoardCanvas
              board={gameState.board}
              onPointClick={handlePointClick}
              highlightedPositions={highlightedPositions}
              selectedPosition={selectedPosition}
              lastMove={lastMove}
              suppressMoveAnimation={isAIThinking}
            />
          </div>
        </div>

        {/* Sidebar — trimmed to 3 panels */}
        <div className="space-y-4">
          <GameInfo gameState={gameState} />

          <MoveHistory
            moves={gameState.moveHistory}
            currentPlayer={gameState.currentPlayer}
          />

          {gameState.status === GameStatus.IN_PROGRESS && gameMode !== 'human-vs-human' && (
            <MoveAnalysis
              gameState={gameState}
              currentPlayer={gameState.currentPlayer}
              isAITurn={isCurrentPlayerAI()}
            />
          )}
        </div>
      </div>

      {/* ── Modals ── */}

      <WelcomeModal
        isOpen={isWelcomeModalOpen && !isModePickerOpen}
        onClose={handleWelcomeClose}
        onShowRules={handleWelcomeShowRules}
      />

      <RulesModal
        isOpen={isRulesModalOpen}
        onClose={() => setIsRulesModalOpen(false)}
      />

      {/* Statistics modal */}
      {isStatsOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
          role="dialog"
          aria-modal="true"
          aria-label="Player statistics"
          onClick={(e) => { if (e.target === e.currentTarget) setIsStatsOpen(false); }}
        >
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-4 border-b">
              <h2 className="text-lg font-bold text-gray-800">📊 Statistics</h2>
              <button
                onClick={() => setIsStatsOpen(false)}
                aria-label="Close statistics"
                className="text-gray-400 hover:text-gray-700 text-2xl leading-none"
              >
                ×
              </button>
            </div>
            <div className="p-4">
              <GameStatistics />
            </div>
          </div>
        </div>
      )}

      {/* Game Over modal */}
      {gameState.status !== GameStatus.IN_PROGRESS && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-2xl p-6 md:p-8 max-w-md w-full text-center">
            <div className="text-6xl mb-4">
              {gameState.status === GameStatus.DRAW
                ? '🤝'
                : gameState.status === GameStatus.TIGER_WIN
                  ? '🐅'
                  : '🐐'}
            </div>
            <h2 className="text-3xl font-bold mb-4">
              {gameState.status === GameStatus.DRAW
                ? 'Game Drawn!'
                : gameState.status === GameStatus.TIGER_WIN
                  ? 'Tigers Win!'
                  : 'Goats Win!'}
            </h2>
            <p className="text-gray-600 mb-6">
              {gameState.status === GameStatus.DRAW
                ? 'The game ended in a draw by mutual agreement.'
                : gameState.status === GameStatus.TIGER_WIN
                  ? `Tigers captured ${gameState.goatsCaptured} goats!`
                  : 'All tigers are blocked!'}
            </p>
            <button
              onClick={handleRequestNewGame}
              className="bg-gradient-to-r from-orange-500 to-amber-500 text-white px-8 py-3 rounded-lg font-semibold hover:from-orange-600 hover:to-amber-600 transition-all transform hover:scale-105"
            >
              Play Again
            </button>
          </div>
        </div>
      )}

      {/* Draw offer modal */}
      <DrawOfferModal
        isOpen={isDrawOfferOpen}
        onAcceptDraw={() => {
          game.declareDraw();
          setIsDrawOfferOpen(false);
          updateGameState();
        }}
        onContinue={() => {
          // Record current threshold so we don't re-prompt until next multiple of 3
          const rep = game.getRepetitionCount();
          const noP = game.getMovesSinceProgress();
          setDrawDeclinedAt(Math.max(rep, noP));
          setIsDrawOfferOpen(false);
        }}
        reason={drawOfferReason}
      />

      {/* Game mode picker modal (shown on reload and before every new game) */}
      {isModePickerOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[60] p-4"
          role="dialog"
          aria-modal="true"
          aria-label="Choose game mode"
        >
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md p-6 md:p-7">
            <h2 className="text-2xl font-bold text-gray-800 mb-2">🎮 Choose Game Mode</h2>
            <p className="text-sm text-gray-600 mb-5">
              Pick who you want to play as for this new game.
            </p>

            <div className="space-y-3">
              <button
                onClick={() => startNewGameWithMode('human-vs-human')}
                className="w-full text-left p-4 rounded-lg border-2 border-gray-200 hover:border-orange-300 bg-white transition-all"
              >
                <div className="font-semibold text-gray-800">👤 vs 👤 Human vs Human</div>
                <div className="text-xs text-gray-600 mt-1">Two players on the same device</div>
              </button>

              <button
                onClick={() => startNewGameWithMode('human-vs-ai')}
                className="w-full text-left p-4 rounded-lg border-2 border-gray-200 hover:border-orange-300 bg-white transition-all"
              >
                <div className="font-semibold text-gray-800">🐐 You as Goats vs 🤖 AI Tigers</div>
                <div className="text-xs text-gray-600 mt-1">Defend and trap the tigers</div>
              </button>

              <button
                onClick={() => startNewGameWithMode('ai-vs-human')}
                className="w-full text-left p-4 rounded-lg border-2 border-gray-200 hover:border-orange-300 bg-white transition-all"
              >
                <div className="font-semibold text-gray-800">🐅 You as Tigers vs 🤖 AI Goats</div>
                <div className="text-xs text-gray-600 mt-1">Hunt goats before getting blocked</div>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Fullscreen board */}
      {isFullscreen && (
        <FullscreenBoard
          board={gameState.board}
          onPointClick={handlePointClick}
          highlightedPositions={highlightedPositions}
          selectedPosition={selectedPosition}
          lastMove={lastMove}
          suppressMoveAnimation={isAIThinking}
          gameState={gameState}
          onClose={() => setIsFullscreen(false)}
        />
      )}
    </div>
  );
};

export default GameContainer;
