// Generated by GitHub Copilot
import React from 'react';
import { AIFactory } from '@/ai';
import { GameStatus } from '@/core/types';

type GameMode = 'human-vs-human' | 'human-vs-ai' | 'ai-vs-human';

interface GameToolbarProps {
  /** Current game mode */
  gameMode: GameMode;
  onGameModeChange: (mode: GameMode) => void;

  /** AI difficulty level 1-5, only relevant when gameMode !== 'human-vs-human' */
  aiDifficulty: number;
  onDifficultyChange: (level: number) => void;

  /** Game action callbacks */
  onNewGame: () => void;
  onUndo: () => void;
  onOpenRules: () => void;
  onOpenStats: () => void;

  canUndo: boolean;
  gameStatus: GameStatus;
  isAIThinking: boolean;
}

const MODES: { value: GameMode; label: string; short: string }[] = [
  { value: 'human-vs-human', label: 'Human vs Human', short: '👤 vs 👤' },
  { value: 'human-vs-ai', label: 'You play Goats vs AI', short: '🐐 vs 🤖' },
  { value: 'ai-vs-human', label: 'You play Tigers vs AI', short: '🐅 vs 🤖' },
];

const DIFFICULTY_LEVELS = [1, 2, 3, 4, 5];

/**
 * GameToolbar renders a horizontal control bar above the board.
 * It replaces the old vertical Game Mode, Difficulty, and Game Controls
 * panels that were crowding the right sidebar.
 *
 * Layout (responsive):
 *   [Mode pills]  |  [Difficulty pills]  |  [Action buttons]
 *
 * Accessibility: all interactive controls have aria-labels and
 * visible focus rings; disabled states use aria-disabled.
 */
const GameToolbar: React.FC<GameToolbarProps> = ({
  gameMode,
  onGameModeChange,
  aiDifficulty,
  onDifficultyChange,
  onNewGame,
  onUndo,
  onOpenRules,
  onOpenStats,
  canUndo,
  isAIThinking,
}) => {
  const isAIMode = gameMode !== 'human-vs-human';

  return (
    <div className="bg-white/95 border border-amber-100 rounded-xl px-3 py-2 mb-4 flex flex-wrap items-center gap-3">

      {/* ── Game Mode ── */}
      <div
        className="flex items-center gap-1 bg-amber-50 rounded-lg p-1"
        role="group"
        aria-label="Game mode"
      >
        {MODES.map(({ value, label, short }) => (
          <button
            key={value}
            onClick={() => onGameModeChange(value)}
            aria-pressed={gameMode === value}
            aria-label={label}
            className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
              gameMode === value
                ? 'bg-amber-500 text-white shadow-sm'
                : 'text-slate-600 hover:bg-amber-100'
            }`}
          >
            {short}
          </button>
        ))}
      </div>

      {/* ── Difficulty (AI modes only) ── */}
      {isAIMode && (
        <div
          className="flex items-center gap-1"
          role="group"
          aria-label="AI difficulty"
        >
          <span className="text-xs text-gray-400 font-medium mr-1 hidden sm:inline">Difficulty:</span>
          {DIFFICULTY_LEVELS.map((level) => {
            const name = AIFactory.getDifficultyName(level);
            const desc = AIFactory.getDifficultyDescription(level);
            const selected = level === aiDifficulty;
            return (
              <button
                key={level}
                onClick={() => onDifficultyChange(level)}
                aria-pressed={selected}
                aria-label={`Difficulty ${name}: ${desc}`}
                title={`${name} — ${desc}${isAIThinking ? ' (takes effect on next AI turn)' : ''}`}
                className={`px-2.5 py-1.5 rounded-md text-xs font-semibold transition-all whitespace-nowrap ${
                  selected
                    ? 'bg-amber-500 text-white shadow-sm'
                    : 'bg-gray-100 text-gray-600 hover:bg-amber-100'
                }`}
              >
                {name}
              </button>
            );
          })}
        </div>
      )}

      {/* ── Spacer ── */}
      <div className="flex-1" />

      {/* ── Actions ── */}
      <div className="flex items-center gap-1" role="group" aria-label="Game actions">
        {/* New Game */}
        <button
          onClick={onNewGame}
          aria-label="New game (Ctrl+N)"
          title="New Game (Ctrl+N)"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold bg-gradient-to-r from-amber-500 to-orange-500 text-white hover:from-amber-600 hover:to-orange-600 transition-all shadow-sm active:scale-95"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          <span className="hidden sm:inline">New</span>
        </button>

        {/* Undo */}
        <button
          onClick={onUndo}
          disabled={!canUndo}
          aria-label="Undo last move (Ctrl+Z)"
          aria-disabled={!canUndo}
          title="Undo (Ctrl+Z)"
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold transition-all shadow-sm active:scale-95 ${
            canUndo
              ? 'bg-blue-500 text-white hover:bg-blue-600'
              : 'bg-gray-100 text-gray-400 cursor-not-allowed'
          }`}
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
          </svg>
          <span className="hidden sm:inline">Undo</span>
        </button>

        {/* Rules */}
        <button
          onClick={onOpenRules}
          aria-label="How to play (H)"
          title="How to Play (H)"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold bg-gray-100 text-gray-700 hover:bg-gray-200 transition-all active:scale-95"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
          </svg>
          <span className="hidden sm:inline">Rules</span>
        </button>

        {/* Stats */}
        <button
          onClick={onOpenStats}
          aria-label="View statistics"
          title="Statistics"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold bg-gray-100 text-gray-700 hover:bg-gray-200 transition-all active:scale-95"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
          </svg>
          <span className="hidden sm:inline">Stats</span>
        </button>
      </div>
    </div>
  );
};

export default GameToolbar;
