// Generated by GitHub Copilot

/**
 * Lightweight Web Audio API sound effects for Bagh Chal.
 * No asset files required — all sounds are synthesised in-browser.
 * AudioContext is lazily created on the first call after a user gesture
 * to comply with browser autoplay policies.
 */

let ctx: AudioContext | null = null;

/** Returns the shared AudioContext, creating it on first use. */
function getCtx(): AudioContext {
  if (!ctx) {
    ctx = new AudioContext();
  }
  // Resume if suspended (browser auto-suspends idle contexts)
  if (ctx.state === 'suspended') {
    ctx.resume();
  }
  return ctx;
}

/**
 * Crisp chess-piece click — white noise burst through a bandpass filter.
 * Short (~60 ms), tactile.
 */
export function playMoveSound(): void {
  try {
    const ac = getCtx();
    const t = ac.currentTime;

    // White noise buffer (short)
    const len = Math.ceil(ac.sampleRate * 0.06);
    const buf = ac.createBuffer(1, len, ac.sampleRate);
    const data = buf.getChannelData(0);
    for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;

    const src = ac.createBufferSource();
    src.buffer = buf;

    // Bandpass to shape the click
    const bp = ac.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 3000;
    bp.Q.value = 1.2;

    const gain = ac.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(0.35, t + 0.003);
    gain.gain.exponentialRampToValueAtTime(0.001, t + 0.06);

    src.connect(bp);
    bp.connect(gain);
    gain.connect(ac.destination);

    src.start(t);
    src.stop(t + 0.06);
  } catch {
    // Silently ignore — sound is non-critical
  }
}

/**
 * Recycle-bin crunch: 3-layer noise burst (low rumble + mid crunch + high crackle).
 * ~200 ms, louder and more textured than the move click.
 */
export function playCaptureSound(): void {
  try {
    const ac = getCtx();
    const t = ac.currentTime;
    const duration = 0.2;

    const len = Math.ceil(ac.sampleRate * duration);
    const buf = ac.createBuffer(1, len, ac.sampleRate);
    const data = buf.getChannelData(0);
    for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;

    // Layer 1 — low rumble
    const s1 = ac.createBufferSource();
    s1.buffer = buf;
    const lp = ac.createBiquadFilter();
    lp.type = 'lowpass';
    lp.frequency.value = 400;
    const g1 = ac.createGain();
    g1.gain.setValueAtTime(0.3, t);
    g1.gain.exponentialRampToValueAtTime(0.001, t + duration);
    s1.connect(lp);
    lp.connect(g1);
    g1.connect(ac.destination);

    // Layer 2 — mid crunch
    const s2 = ac.createBufferSource();
    s2.buffer = buf;
    const bp = ac.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 1500;
    bp.Q.value = 0.8;
    const g2 = ac.createGain();
    g2.gain.setValueAtTime(0.4, t);
    g2.gain.exponentialRampToValueAtTime(0.001, t + duration * 0.7);
    s2.connect(bp);
    bp.connect(g2);
    g2.connect(ac.destination);

    // Layer 3 — high crackle
    const s3 = ac.createBufferSource();
    s3.buffer = buf;
    const hp = ac.createBiquadFilter();
    hp.type = 'highpass';
    hp.frequency.value = 4000;
    const g3 = ac.createGain();
    g3.gain.setValueAtTime(0.15, t);
    g3.gain.exponentialRampToValueAtTime(0.001, t + duration * 0.5);
    s3.connect(hp);
    hp.connect(g3);
    g3.connect(ac.destination);

    s1.start(t); s1.stop(t + duration);
    s2.start(t); s2.stop(t + duration);
    s3.start(t); s3.stop(t + duration);
  } catch {
    // Silently ignore
  }
}

/**
 * A short ascending chime triad played when the game ends.
 * Three staggered sine tones building a major chord.
 */
export function playWinSound(): void {
  try {
    const ac = getCtx();
    const notes = [523.25, 659.25, 783.99]; // C5, E5, G5

    notes.forEach((freq, i) => {
      const osc = ac.createOscillator();
      const gain = ac.createGain();
      const delay = i * 0.12;

      osc.type = 'sine';
      osc.frequency.setValueAtTime(freq, ac.currentTime + delay);

      osc.connect(gain);
      gain.connect(ac.destination);

      const t = ac.currentTime + delay;
      gain.gain.setValueAtTime(0, t);
      gain.gain.linearRampToValueAtTime(0.2, t + 0.01);
      gain.gain.exponentialRampToValueAtTime(0.001, t + 0.5);
      osc.start(t);
      osc.stop(t + 0.52);
    });
  } catch {
    // Silently ignore
  }
}
