// Generated by GitHub Copilot

/**
 * Lightweight Web Audio API sound effects for Bagh Chal.
 * No asset files required — all sounds are synthesised in-browser.
 * AudioContext is lazily created on the first call after a user gesture
 * to comply with browser autoplay policies.
 */

let ctx: AudioContext | null = null;

/** Returns the shared AudioContext, creating it on first use. */
function getCtx(): AudioContext {
  if (!ctx) {
    ctx = new AudioContext();
  }
  // Resume if suspended (browser auto-suspends idle contexts)
  if (ctx.state === 'suspended') {
    ctx.resume();
  }
  return ctx;
}

/**
 * Schedules a short envelope on a gain node and disconnects it when done.
 * @param gainNode - The gain to ramp
 * @param peak     - Peak gain value
 * @param attack   - Attack duration in seconds
 * @param duration - Total duration in seconds
 */
function fireEnvelope(
  gainNode: GainNode,
  source: AudioScheduledSourceNode,
  ac: AudioContext,
  peak: number,
  attack: number,
  duration: number,
): void {
  const t = ac.currentTime;
  gainNode.gain.setValueAtTime(0, t);
  gainNode.gain.linearRampToValueAtTime(peak, t + attack);
  gainNode.gain.exponentialRampToValueAtTime(0.001, t + duration);
  source.start(t);
  source.stop(t + duration + 0.01);
}

/**
 * A soft descending sine blip played on every successful move.
 * Short (~80 ms), non-intrusive.
 */
export function playMoveSound(): void {
  try {
    const ac = getCtx();
    const osc = ac.createOscillator();
    const gain = ac.createGain();

    osc.type = 'sine';
    osc.frequency.setValueAtTime(520, ac.currentTime);
    osc.frequency.exponentialRampToValueAtTime(340, ac.currentTime + 0.08);

    osc.connect(gain);
    gain.connect(ac.destination);

    fireEnvelope(gain, osc, ac, 0.18, 0.005, 0.1);
  } catch {
    // Silently ignore — sound is non-critical
  }
}

/**
 * A sharper triangle-wave knock played when a goat is captured.
 * Slightly louder and higher-pitched than the move sound.
 */
export function playCaptureSound(): void {
  try {
    const ac = getCtx();
    const osc = ac.createOscillator();
    const gain = ac.createGain();

    osc.type = 'triangle';
    osc.frequency.setValueAtTime(700, ac.currentTime);
    osc.frequency.exponentialRampToValueAtTime(280, ac.currentTime + 0.12);

    osc.connect(gain);
    gain.connect(ac.destination);

    fireEnvelope(gain, osc, ac, 0.28, 0.004, 0.14);
  } catch {
    // Silently ignore
  }
}

/**
 * A short ascending chime triad played when the game ends.
 * Three staggered sine tones building a major chord.
 */
export function playWinSound(): void {
  try {
    const ac = getCtx();
    const notes = [523.25, 659.25, 783.99]; // C5, E5, G5

    notes.forEach((freq, i) => {
      const osc = ac.createOscillator();
      const gain = ac.createGain();
      const delay = i * 0.12;

      osc.type = 'sine';
      osc.frequency.setValueAtTime(freq, ac.currentTime + delay);

      osc.connect(gain);
      gain.connect(ac.destination);

      const t = ac.currentTime + delay;
      gain.gain.setValueAtTime(0, t);
      gain.gain.linearRampToValueAtTime(0.2, t + 0.01);
      gain.gain.exponentialRampToValueAtTime(0.001, t + 0.5);
      osc.start(t);
      osc.stop(t + 0.52);
    });
  } catch {
    // Silently ignore
  }
}
